require('plugins')
require('colors')
require('settings')
require('autocmds')
require('remaps')

-- plugin settings
require('plugins.lsp')
require('plugins.treesitter')
require('plugins.autopairs')
require('plugins.telescope')
require('plugins.lualine')
require('plugins.harpoon')
require('plugins.lazygit')
require('plugins.gitsigns')
require('plugins.toggleterm')
